### ISSUE TITLE
Can't use renderer name as renderer input when deploying

### ISSUE THREAD

**Issue by joshiefishbein** [spirit-fish/cli#2]
**Describe the bug**
The screenshot on https://www.spirit.fish/features/deployments describes the CLI to require the renderer's name when deploying, but the CLI returns `Request failed with status code 404` as if it can't find the renderer by its name. Using the UUID instead works as expected.

**To Reproduce**
1. Install CLI
2. Run `spirit-fish authenticate`
3. Authenticate in browser
4. Run `spirit-fish renderers`
5. Run `spirit-fish deploy "Renderer Name" ./build --activate` after copying the name from the renderers list

**Expected behavior**
I expected the deploy to work as documented.

**Desktop**
 - Device: [e.g. Late-2016 MBP 15"]
 - OS: MacOS 10.15.7
 - Version `0.0.8`
 - Node `v12.19.0`

**Comment by hhff** [comment]
fixed in v0.0.9!
